config/routes.rb
Sokura::Application.routes.draw do

   root :to => 'home#index'
   
   resources :articles
   resources :events
   
   get '/der_liederhof' => 'pages#about'
   get '/foerderverein' => 'pages#booster'
   get '/kontakt' => 'pages#contact'
   get '/ihre_hilfe' => 'pages#donation'
   get '/anfahrt' => 'pages#location'
   get '/imprint' => 'pages#imprint'
   
   

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :find_base_data
  
  
  
 private
  
  
  def find_base_data
    @events = Event.all
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def show
    @article = Article.find_by_id(params[:id])
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end
  
  def show
    @event = Event.find_by_id(params[:id])
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @articles = Article.all 
    
    respond_to do |wants|
      wants.html
      wants.js
    end

  end
  
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  

  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def page_title
    t("#{controller_path.split('/').join('.')}.#{action_name}.pagetitle") +  " | SozialKulturRaum - Sokura"
  end
  
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.haml
.article
  .date
    %span= l(article.created_at.to_date).html_safe
  .title= article.title
  .description= article.text
  .read_more=link_to "Ganzen Beitrag anzeigen", [article]

app/views/articles/show.html.haml
%h2.green= @article.title
.text= @article.text

app/views/events/_event.html.haml
=link_to [event] do
  .title=event.title
  .date= l(event.date, format: :long)
%hr

app/views/events/index.html.haml
- content_for :events do
  = render @events

app/views/events/show.html.haml
%h2.green= @event.title
.text=@event.text

app/views/home/index.html.haml
%h2.green Neues aus dem SozialKulturRaum
.articles=render @articles

app/views/layouts/application.html.haml
!!! 5

%head
  %meta{ :charset => "utf-8" }
  %title= page_title
  = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
  = javascript_include_tag "application", "data-turbolinks-track" => true
  = csrf_meta_tags

%body
  #wrapper
    %header
      #logo-box=link_to image_tag("Logo_colored.png"), root_path
      #top-info-box
        %ul
          %li.drive=link_to "Anfahrt", anfahrt_path
          %li.mail=mail_to "info@sakuro.de", "Mail: info@sakura.de"
          %li.tel Tel: xxx / YY 33 44 55
      .placeholder
      #pitch
        %h1 Willkommen im <span style="color:#C30075">So</span>zial<span style="color:#C30075">Ku</span>ltur<span style="color:#C30075">Ra</span>um auf dem Liederhof
        #hof-overview=image_tag("Luftbildlogo.gif")
      .placeholder
      #menu-bar
        %ul
          %li=link_to 'Startseite', root_path, :class => current_page?(root_path) ? "active" : ""
          %li=link_to 'Der Liederhof', der_liederhof_path, :class => current_page?(der_liederhof_path) ? "active" : ""
          %li=link_to 'Der Förderverein', foerderverein_path, :class => current_page?(foerderverein_path) ? "active" : ""
          %li=link_to 'Ihre Hilfe', ihre_hilfe_path, :class => current_page?(ihre_hilfe_path) ? "active" : ""
          %li=link_to 'Kontakt', kontakt_path, :class => current_page?(kontakt_path) ? "active" : ""
          
    #content
      #main= yield
      #events
        %h2 Veranstaltungen
        %hr
        =render @events
      #gallery
        %h2 Gallerie
        %hr
        Die ersten Bilder kommen bald

    #footer
      #menu
        %ul
          %li= link_to 'Impressum', imprint_path
          %li= link_to 'Kontakt', kontakt_path
          %li= link_to 'Über Sokura', der_liederhof_path
      #created
        %hr
        created by Maximilian Woltersdorf

app/views/pages/about.html.haml
%h2.green Der Liederhof
%br
.text
  In dem schönen Ort Pannigkau (Ortsteil von Kemberg), in der Pannigkauer Dorfstr. 15, entsteht ein Kulturhof mit sozialem Selbstverständnis. Der Ort Pannigkau bietet durch seinen   historischen Charakter mit der Kastanien- und Lindenallee touristischen, aber auch nachbarschaftlichen Reiz. Der Vierseitenhof Nr. 15 atmet ebenfalls noch diese Atmosphäre. Dabei stehen die vier Seiten im Namen des Kulturhofes für die vier inhaltlichen Pfeiler des Hofes: 
#luftbildlogo
%ul.about
  %li Sozial
  %li Kultur
  %li Bildung
  %li Nachbarschaft
  
.clearfix

%p.text 
  Der Liederhof soll in Zukunft Unterschiedliches beherbergen. 
  Er soll ein Ort der Begegnung, des Austausches und des kreativen Tuns sein. 
  Natürlich werden auf dem Liederhof aber auch Konzerte des deutschen Liedguts stattfinden.
  Wer den Initiator kennt, weiß, warum:

%h3 Der Initiator
.text
  Den unter Ensembleschutz stehenden Hof hat Günther Hornberger, einer der Gründungsmitglieder, 
  vor kurzem erworben. Er ist zum einem seit vielen, vielen Jahren als Sozialarbeiter tätig:
  %br
  %br
  %ul.arrows
    %li Soziale Gruppenarbeit mit Kindern und Jugendlichen
    %li Hilfe zur Erziehung (Einzel- und Gruppenarbeit)
    %li Schulsozialarbeit
    %li Präventionsarbeit gegen sexuellen Missbrauch
    %li im Bereich mit Menschen mit Beeinträchtigung (Schule und Reisebegleitung)
    %li diverse Gruppenarbeit mit Erwachsenen (Elterngruppen, Schuldenprävention, Kreatives Schreiben)
    %li Bachelorabschluss mit Auszeichnung und Fachveröffentlichung zum Thema "Inklusion und Sozialraum"
    %li Regisseur/Theaterleiter des Amateur- Theaters "Theater in der Scheune" - Schönwalde-Glien
    %li z.Zt. an der Schnittstelle Sozialarbeit/Kultursozialarbeit tätig im ESF-geförderten "Projektladen Drewitz" Potsdam
  %br
  Zum anderen ist er von Jugend an freischaffender Künstler: 
  %br
  %br
  %ul.arrows
    %li Liedermacher (Preisträger der „Goldenen Hoyschrecke“, außerordentliches GEMA-Mitglied, z.Zt. im Vorstand des Landesverbandes PROFOLK Berlin e.V.)
    %li Autor von Lyrik und Prosa (ehemals Mitglied im VS Berlin, bis vor kurzem Vorsitzender des Literatur-Kollegiums-Brandenburg e.V.)
    %li Kindertheaterautor, -schauspieler und -regisseur
    %li Lyrikübersetzung aus dem Spanischen
    %li zwei Jahre Betrieb einer Galerie für Angewandte Kunst "Form & Stil" in Berlin-Wilmersdorf.
    

app/views/pages/booster.html.haml
%h2.green Der Förderverein
.text.margin
  Der Liederhof ist ein alter Vierseitenhof, Baujahr 1889. Die vier Seiten des Kulturhofes spiegeln sich auch in den dort geplanten Angeboten wieder:
%br
%br
%h3 A) Sozial: 
%ol.left
  %li Offene Sozialberatung
  %li Offene Erziehungsberatung
  %li Präventive Schuldnerberatung
  %li Betreuungsangebote
  %li „Dorfkümmerer“
  //%li Einrichtung einer Facherziehungsstelle auf dem Hof (Günther Hornberger für Kurs-Wechsel e.V.)
  

#theater
%h3 B) Kultur:
%ol.left
  %li Dorf-Theater (Amateur) unter der künstlerischen Leitung von Günther Hornberger, der u.a. die letzten drei Jahre das Theater in der Scheune – Schönwalde-Glien geleitet hat. 
  %li Einrichtung eines Aufenthaltsstipendiums für Künstlerinnen und Künstler, die mindestens zwei Kunstformen aktiv bedienen (bspw. Musik/Text, Text/Bühne, Bühnenbild/Musik)
  %li Kleinkunstveranstaltungen (Liedermacher, Kabarett)
  %li Lesungen, Vorträge, Konzerte
  //%li Verlagsarbeit (ab 2015)
  

#learning
%h3.right C) Bildung:
%ol.right
  %li Kurse und Projekte zu verschiedenen Inhalte (Schreibwerkstatt, Malen, Kräuterlerngarten etc.) 
  %li ehrenamtlich organisierte Schülerhilfe
  %li Leihbücherei und Lesezirkel
  %li gesundheitsfördernde Sportangebote 
  %li Projekte mit Kitas und Schulen im Verbund
  
.clearfix

%h3 D) Nachbarschaft
%ol
  %li Freizeitangebote für Jung und Alt (Boule)
  %li kleine Dorf- oder Hoffeste zu besonderen Anlässen
  %li Überlassung der Gemeinschaftsräume für Familienfeiern etc.
  %li Netzwerkarbeit im Ort, in der Region, im Landkreis und darüber hinaus
  %li Angebote, die von den Bewohnern selbst kommen, werden gefördert
  

  
  

app/views/pages/contact.html.haml
%h2.green Kontakt

app/views/pages/donation.html.haml
%h2.green Spendenaufruf
.text.margin
  Der gemeinnützige Verein „SozialKulturRaum e.V.“ hat sich vieles vorgenommen und auch schon einiges davon auf den Weg gebracht. Zum Beispiel ist der Verein nun im Vereinsregister Stendal eingetragen und hat die Anerkennung der Gemeinnützigkeit Seitens des Finanzamtes für Körperschaften.
  %br
  %br
  Zudem hat sich unter der Leitung unseres Vorsitzenden bereits eine Theater/Kabarettgruppe gegründet, die sich regelmäßig auf dem Hof trifft und übrigens noch Mitmacherinnen und Mitmacher sucht, ob nun vor, hinter oder auf der Bühne. Um später nach den Proben überhaupt Theater aufführen zu können, müssen der Theaterraum (Stall) und die Gästetoiletten in der Waschküche nebenan ausgebaut werden. Alles natürlich unter Berücksichtigung bauordnungsamtlicher Auflagen (Brandschutz, Fluchtmöglichkeiten etc.).
  %br
  %br
  Für den geplanten Kräuterlerngarten ist das erste Beet schon vorbereitet und wartet darauf, bestückt zu werden.
  %br
  %br
  Und das erste Fest für die Dorfbewohner von Pannigkau und Gäste fand bereits statt am 2. Advent 2013. Dafür hat es schon viele Unterstützer geben. Das finden wir besonders toll. Danke an dieser Stelle. 
  
  %br
  %br
  Im Frühjahr soll auch die Boulebahn gebaut werden, damit dann jede/r, die/der Lust hat, jeden Sonntag um 10:30 Uhr Boule spielen kann. Der Verein ist dafür übrigens auf der Suche nach Eisenbahnschwellen als Begrenzung.
  %br
  %br
  Das alles wird viele Unterstützer, das heißt Mitmacherinnen/Mitmacher und auch einiges Geld brauchen. Und nicht alles wird der Verein allein „erwirtschaften“  oder durch Fördergelder sammeln können. Deshalb hier die Bitte, nicht zu zögern unsere Vorhaben auch finanziell zu unterstützen. Das geht entweder als Fördermitglied, und damit regelmäßig, oder wie es gerade passt. Und mal ganz ehrlich, jeder Betrag, wenn auch noch so klein, hilft.
  %br
  %br
  Natürlich stellen wir auf Wunsch eine Spendenquittung aus.
  %br
  %br
  Wir danken im Voraus und grüßen nachbarschaftlich.

#donation-box
  %h3 Spenden an:
  %table
    %tr
      %td Kontoinhaber: 
      %td SozialKulturRaum e.V.
    %tr  
      %td Konto: 
      %td 101014414
    %tr
      %td BLZ:
      %td 80550101
    %tr
      %td Vereinsregisternummer:
      %td Amtsgericht Stendal / VR3660

  

app/views/pages/imprint.haml
%h2.green Impressum
.text.margin
  %ul

    %li SozialKulturRaum e. V.
    %li Pannigkauer Dorfstr. 15
    %li D-06901 Kemberg / Pannigkau
  %br
  %h3 Kontakt
  %ul
    %li HORNBERGER, Günther W.
    %li Fon: 034921-233020
    %li mobil: 0157-74748624
    %li.mail 
      E-Mail: 
      =mail_to "hornberger@liedkunst.de", "Mail: hornberger@liedkunst.de"
  %br
  %br     
  %h3 Datenschutzerklärung:
  %p
    %strong Datenschutzerklärung für die Nutzung von Google Analytics
  %p Diese Website benutzt Google Analytics, einen Webanalysedienst der Google Inc. ("Google"). Google Analytics verwendet sog. "Cookies", Textdateien, die auf Ihrem Computer gespeichert werden und die eine Analyse der Benutzung der Website durch Sie ermöglichen. Die durch den Cookie erzeugten Informationen über Ihre Benutzung dieser Website werden in der Regel an einen Server von Google in den USA übertragen und dort gespeichert. Im Falle der Aktivierung der IP-Anonymisierung auf dieser Webseite wird Ihre IP-Adresse von Google jedoch innerhalb von Mitgliedstaaten der Europäischen Union oder in anderen Vertragsstaaten des Abkommens über den Europäischen Wirtschaftsraum zuvor gekürzt.
  %p Nur in Ausnahmefällen wird die volle IP-Adresse an einen Server von Google in den USA übertragen und dort gekürzt. Im Auftrag des Betreibers dieser Website wird Google diese Informationen benutzen, um Ihre Nutzung der Website auszuwerten, um Reports über die Websiteaktivitäten zusammenzustellen und um weitere mit der Websitenutzung und der Internetnutzung verbundene Dienstleistungen gegenüber dem Websitebetreiber zu erbringen. Die im Rahmen von Google Analytics von Ihrem Browser übermittelte IP-Adresse wird nicht mit anderen Daten von Google zusammengeführt.
  %p
    Sie können die Speicherung der Cookies durch eine entsprechende Einstellung Ihrer Browser-Software verhindern; wir weisen Sie jedoch darauf hin, dass Sie in diesem Fall gegebenenfalls nicht sämtliche Funktionen dieser Website vollumfänglich werden nutzen können. Sie können darüber hinaus die Erfassung der durch das Cookie erzeugten und auf Ihre Nutzung der Website bezogenen Daten (inkl. Ihrer IP-Adresse) an Google sowie die Verarbeitung dieser Daten durch Google verhindern, indem sie das unter dem folgenden Link verfügbare Browser-Plugin herunterladen und installieren:
    = succeed "." do
      %a{href: "http://tools.google.com/dlpage/gaoptout?hl=de"} http://tools.google.com/dlpage/gaoptout?hl=de
  %p  
  %p
    %i
      Quellenangaben:
      %a{href: "http://www.google.com/intl/de/analytics/privacyoverview.html", rel: "nofollow", target: "_blank"} Google Analytics Datenschutzerklärungt24.de/muster-disclaimer.html", rel: "nofollow", target: "_blank"} Disclaimer eRecht24

app/views/pages/location.html.haml
%h2.green Anfahrt
.text
  %h3 Die Anschrift des Hofes:
  %br
  Pannigkauer Dorfstrasse 15
  %br
  06901 Pannigkau, Eutzsch ‎
  
  %h3 Kartenansicht
  %iframe{frameborder: "0", height: "550", marginheight: "0", marginwidth: "0", scrolling: "no", src: "https://maps.google.de/maps?f=q&source=s_q&hl=de&geocode=&q=Dorfstra%C3%9Fe+15,+06901,+Pannigkau,+Eutzsch&aq=&sll=51.810922,12.624773&sspn=0.011263,0.0159&ie=UTF8&hq=&hnear=Dorfstra%C3%9Fe+15,+Pannigkau+06888+Eutzsch&ll=51.810923,12.624772&spn=0.011263,0.0159&t=m&z=14&output=embed", width: "600"}
  %br/
  %small
    %a{href: "https://maps.google.de/maps?f=q&source=embed&hl=de&geocode=&q=Dorfstra%C3%9Fe+15,+06901,+Pannigkau,+Eutzsch&aq=&sll=51.810922,12.624773&sspn=0.011263,0.0159&ie=UTF8&hq=&hnear=Dorfstra%C3%9Fe+15,+Pannigkau+06888+Eutzsch&ll=51.810923,12.624772&spn=0.011263,0.0159&t=m&z=14", target: "_blank", style: "color:#0000FF;text-align:left"} Größere Kartenansicht
    
    